# Problem Set 6 - Intro to Opt

In [3]:
import cvxpy as cp
import numpy as np

CVXPY Package 

In [76]:
import cvxpy as cp
import numpy as np

# Problem data.

np.random.seed(314)
x = np.random.randn(40, 1)
y = np.random.randn(40,1)

In [33]:
a = np.zeros((10,2))

a[1] = (1,2)
a

array([[0., 0.],
       [1., 2.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [80]:
x[1]

array([0.78196448])

In [79]:
float(x[1])

0.7819644825116457

In [36]:
a = np.array([])
np.append(a, (1,2))

array([1., 2.])

In [81]:
group = np.zeros(40)
A1 = np.empty((0,2), int)
A2 = np.empty((0,2), int)

for i in range(len(x)):
    group = (2*x[i]) < (y[i]+0.5)
    if group:
        A1 = np.append(A1, [[float(x[i]), float(y[i])]], axis=0)
    else:
        A2 = np.append(A2, [[float(x[i]), float(y[i])]], axis=0)

In [82]:
A1

array([[-0.70707096, -0.84956149],
       [-0.93165719,  0.98628471],
       [-0.22178966,  1.70984745],
       [-0.77257544, -0.27393571],
       [-0.28126003, -0.40426538],
       [-0.93192543, -0.89955014],
       [-0.49853725, -0.45587449],
       [ 0.19150443,  0.65897885],
       [-0.61876383, -1.15106527],
       [-1.86605484,  0.36346598],
       [-0.63641398,  1.48327704],
       [-0.76091643, -0.28145836],
       [ 0.18136585,  0.24367764],
       [ 0.43781928,  0.86221593],
       [-1.52956799,  1.41368913],
       [-0.33748039, -0.44068334],
       [-0.96137142,  1.20110936],
       [-1.14722501, -0.15802795],
       [-0.42294534, -0.67009457],
       [-0.92783383,  1.2861011 ],
       [ 0.10527984,  0.15637034],
       [-1.09755663, -0.83163134],
       [-0.87038088,  1.89373309]])

In [2]:
# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A*x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)

Object `np.find` not found.


Object `np.find` not found.
